# Generated by Django 4.2.9 on 2024-01-19 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="InstrumentFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MusicItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("composer", models.CharField(max_length=200)),
                ("duration", models.DurationField()),
                ("notes", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("publicDescription", models.TextField()),
                ("privateDescription", models.TextField()),
                ("published", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Rehearsal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("startDate", models.DateField()),
                ("startTime", models.TimeField()),
                ("endTime", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="RentalContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("supplier", models.CharField(max_length=200)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("postcode", models.CharField(max_length=200)),
                ("contactName", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("website", models.CharField(max_length=200)),
                ("directions", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="RehearsalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "musicItem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="music.musicitem",
                    ),
                ),
                (
                    "rehearsal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="music.rehearsal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rehearsal",
            name="rehearsalItems",
            field=models.ManyToManyField(
                through="music.RehearsalItem", to="music.musicitem"
            ),
        ),
        migrations.AddField(
            model_name="rehearsal",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="music.venue"
            ),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstNames", models.CharField(max_length=200)),
                ("lastName", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("member", models.BooleanField(default=False)),
                ("instruments", models.ManyToManyField(to="music.instrument")),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceSeats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="music.instrument",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="music.performance",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="music.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "musicItem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="music.musicitem",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="music.performance",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="performance",
            name="performanceItems",
            field=models.ManyToManyField(
                through="music.PerformanceItem", to="music.musicitem"
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="music.venue"
            ),
        ),
        migrations.CreateModel(
            name="MusicItemPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.CharField(max_length=200)),
                ("desk", models.IntegerField()),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="music.instrument",
                    ),
                ),
                (
                    "musicItem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="music.musicitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="musicitem",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="music.rentalcontract"
            ),
        ),
        migrations.AddField(
            model_name="musicitem",
            name="parts",
            field=models.ManyToManyField(
                through="music.MusicItemPart", to="music.instrument"
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="music.instrumentfamily"
            ),
        ),
    ]
