# Generated by Django 4.2.9 on 2024-06-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_alter_musicitem_contract"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="musicitem",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="musicitem",
            name="parts",
        ),
        migrations.RemoveField(
            model_name="musicitempart",
            name="instrument",
        ),
        migrations.RemoveField(
            model_name="musicitempart",
            name="musicItem",
        ),
        migrations.RemoveField(
            model_name="performance",
            name="performanceItems",
        ),
        migrations.RemoveField(
            model_name="performance",
            name="venue",
        ),
        migrations.RemoveField(
            model_name="performanceitem",
            name="musicItem",
        ),
        migrations.RemoveField(
            model_name="performanceitem",
            name="performance",
        ),
        migrations.RemoveField(
            model_name="performanceseats",
            name="instrument",
        ),
        migrations.RemoveField(
            model_name="performanceseats",
            name="performance",
        ),
        migrations.RemoveField(
            model_name="performanceseats",
            name="person",
        ),
        migrations.RemoveField(
            model_name="person",
            name="instruments",
        ),
        migrations.RemoveField(
            model_name="rehearsal",
            name="rehearsalItems",
        ),
        migrations.RemoveField(
            model_name="rehearsal",
            name="venue",
        ),
        migrations.RemoveField(
            model_name="rehearsalitem",
            name="musicItem",
        ),
        migrations.RemoveField(
            model_name="rehearsalitem",
            name="rehearsal",
        ),
        migrations.DeleteModel(
            name="Instrument",
        ),
        migrations.DeleteModel(
            name="InstrumentFamily",
        ),
        migrations.DeleteModel(
            name="MusicItem",
        ),
        migrations.DeleteModel(
            name="MusicItemPart",
        ),
        migrations.DeleteModel(
            name="Performance",
        ),
        migrations.DeleteModel(
            name="PerformanceItem",
        ),
        migrations.DeleteModel(
            name="PerformanceSeats",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="Rehearsal",
        ),
        migrations.DeleteModel(
            name="RehearsalItem",
        ),
        migrations.DeleteModel(
            name="RentalContract",
        ),
        migrations.DeleteModel(
            name="Venue",
        ),
    ]
