# Generated by Django 4.2.30 on 2026-05-04 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orman.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('firstNames', models.CharField(max_length=200, verbose_name='first names')),
                ('lastName', models.CharField(max_length=200, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('member', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('dismissible', models.BooleanField(default=True)),
                ('visibleFrom', models.DateTimeField(blank=True, null=True, verbose_name='visible from')),
                ('visibleUntil', models.DateTimeField(blank=True, null=True, verbose_name='visible until')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('manual', 'Manual / CSV export'), ('google_groups', 'Google Groups'), ('mailchimp', 'Mailchimp'), ('brevo', 'Brevo')], default='manual', max_length=20)),
                ('filter_type', models.CharField(choices=[('manual', 'Manual membership'), ('all_members', 'All active members'), ('instrument', 'Instrument (all players)'), ('instrument_family', 'Instrument family / section')], default='manual', help_text='Manual: you control membership. Dynamic options recompute from the roster automatically when you reconcile.', max_length=20, verbose_name='membership filter')),
                ('address', models.EmailField(blank=True, help_text='The display email address for this list (e.g. members@myorchestra.com).', max_length=254, verbose_name='group/list email')),
                ('description', models.TextField(blank=True)),
                ('api_key', models.CharField(blank=True, help_text='Mailchimp or Brevo API key. Leave blank for manual/Google-Groups lists.', max_length=500, verbose_name='API key')),
                ('list_id', models.CharField(blank=True, help_text='Mailchimp: audience ID (Audience → Settings). Brevo: numeric list ID. Google Groups: group email address.', max_length=200, verbose_name='list / audience / group ID')),
                ('google_service_account_json', models.TextField(blank=True, help_text='Google Groups only: paste the full service-account JSON key here. The service account needs domain-wide delegation with https://www.googleapis.com/auth/admin.directory.group.member scope.', verbose_name='Google service-account JSON')),
                ('google_delegated_admin', models.EmailField(blank=True, help_text='Google Groups only: an admin account to impersonate (e.g. admin@myorchestra.com).', max_length=254, verbose_name='Google delegated-admin email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filter_instrument', models.ForeignKey(blank=True, help_text="Required when filter is 'Instrument'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='orman.instrument', verbose_name='instrument (filter)')),
                ('filter_instrument_family', models.ForeignKey(blank=True, help_text="Required when filter is 'Instrument family / section'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='orman.instrumentfamily', verbose_name='instrument family (filter)')),
            ],
            options={
                'verbose_name': 'mailing list',
                'verbose_name_plural': 'mailing lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MusicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('composer', models.CharField(blank=True, max_length=200)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('score_file', models.FileField(blank=True, null=True, upload_to='scores/', verbose_name='score file')),
                ('external_link', models.URLField(blank=True, verbose_name='external link')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('publicDescription', models.TextField(blank=True, verbose_name='public description')),
                ('privateDescription', models.TextField(blank=True, verbose_name='private description')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('show_as_banner', models.BooleanField(default=False, verbose_name='show as banner')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('startDate', models.DateField(verbose_name='start date')),
                ('startTime', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('endTime', models.TimeField(blank=True, null=True, verbose_name='end time')),
            ],
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('supplier', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=200)),
                ('contactName', models.CharField(blank=True, max_length=200, verbose_name='contact name')),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('directions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', 'Going'), ('maybe', 'Maybe'), ('no', 'Not going')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='orman.performance')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL)),
                ('playing_instruments', models.ManyToManyField(blank=True, related_name='rsvps', to='orman.instrument', verbose_name='playing instruments')),
                ('rehearsal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='orman.rehearsal')),
            ],
        ),
        migrations.CreateModel(
            name='RehearsalSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every two weeks')], default='weekly', max_length=20, verbose_name='frequency')),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of week')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('series_start', models.DateField(verbose_name='series start')),
                ('series_end', models.DateField(blank=True, null=True, verbose_name='series end')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orman.venue')),
            ],
            options={
                'verbose_name_plural': 'rehearsal series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RehearsalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('musicItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orman.musicitem')),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orman.rehearsal')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='rehearsalItems',
            field=models.ManyToManyField(through='orman.RehearsalItem', to='orman.musicitem'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehearsals', to='orman.rehearsalseries'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orman.venue'),
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='question text')),
                ('kind', models.CharField(choices=[('free_text', 'Free text'), ('single_choice', 'Single choice'), ('multi_choice', 'Multiple choice')], default='free_text', max_length=20, verbose_name='type')),
                ('order', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='orman.poll')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='orman.pollquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='orman.pollchoice')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='orman.pollquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orman.instrument')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orman.performance')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('musicItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orman.musicitem')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orman.performance')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='performanceItems',
            field=models.ManyToManyField(through='orman.PerformanceItem', to='orman.musicitem'),
        ),
        migrations.AddField(
            model_name='performance',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orman.venue'),
        ),
        migrations.CreateModel(
            name='MusicItemPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=orman.models._part_upload_to, verbose_name='file upload')),
                ('external_link', models.URLField(blank=True, verbose_name='external link')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orman.instrument')),
                ('musicItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orman.musicitem')),
            ],
            options={
                'ordering': ['instrument__name'],
            },
        ),
        migrations.AddField(
            model_name='musicitem',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orman.rentalcontract'),
        ),
        migrations.AddField(
            model_name='musicitem',
            name='parts',
            field=models.ManyToManyField(through='orman.MusicItemPart', to='orman.instrument'),
        ),
        migrations.CreateModel(
            name='MailingListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error')], default='pending', max_length=10)),
                ('sync_error', models.CharField(blank=True, max_length=500)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_members', to='orman.mailinglist')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['person__lastName', 'person__firstNames'],
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orman.instrumentfamily'),
        ),
        migrations.CreateModel(
            name='AnnouncementDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissedAt', models.DateTimeField(auto_now_add=True, verbose_name='dismissed at')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='orman.announcement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='orman.instrument'),
        ),
        migrations.AddField(
            model_name='person',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='rsvp',
            constraint=models.UniqueConstraint(condition=models.Q(('rehearsal__isnull', False)), fields=('person', 'rehearsal'), name='unique_rsvp_rehearsal'),
        ),
        migrations.AddConstraint(
            model_name='rsvp',
            constraint=models.UniqueConstraint(condition=models.Q(('performance__isnull', False)), fields=('person', 'performance'), name='unique_rsvp_performance'),
        ),
        migrations.AddConstraint(
            model_name='rsvp',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('performance__isnull', True), ('rehearsal__isnull', False)), models.Q(('performance__isnull', False), ('rehearsal__isnull', True)), _connector='OR'), name='rsvp_exactly_one_event'),
        ),
        migrations.AddConstraint(
            model_name='pollanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('choice__isnull', True)), fields=('question', 'person'), name='unique_freetext_answer'),
        ),
        migrations.AddConstraint(
            model_name='pollanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('choice__isnull', False)), fields=('question', 'person', 'choice'), name='unique_choice_answer'),
        ),
        migrations.AddConstraint(
            model_name='mailinglistmember',
            constraint=models.UniqueConstraint(fields=('mailing_list', 'person'), name='unique_mailinglist_member'),
        ),
        migrations.AddConstraint(
            model_name='announcementdismissal',
            constraint=models.UniqueConstraint(fields=('announcement', 'person'), name='unique_dismissal'),
        ),
    ]
