# Generated by Django 4.2.30 on 2026-05-06 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='calendar_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
