# Generated by Django 4.2.30 on 2026-09-15 10:39

from django.db import migrations, models
import orman.models


class Migration(migrations.Migration):

    dependencies = [
        ("orman", "0003_passkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=orman.models._carousel_upload_to),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Shown on the public home page. Supports Markdown formatting.",
                        verbose_name="description",
                    ),
                ),
                (
                    "contactName",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="contact name"
                    ),
                ),
                (
                    "contactEmail",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="contact email"
                    ),
                ),
                (
                    "contactPhone",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="contact phone"
                    ),
                ),
                (
                    "contactAddress",
                    models.TextField(blank=True, verbose_name="contact address"),
                ),
            ],
            options={
                "verbose_name_plural": "site content",
            },
        ),
    ]
