# Generated by Django 4.2.30 on 2026-09-16 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orman", "0004_carouselimage_sitecontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicitempart",
            name="instruments",
            field=models.ManyToManyField(
                blank=True, related_name="music_item_parts", to="orman.instrument"
            ),
        ),
        migrations.AddField(
            model_name="musicitempart",
            name="is_score",
            field=models.BooleanField(default=False, verbose_name="full score"),
        ),
        migrations.AlterField(
            model_name="musicitempart",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orman.instrument",
            ),
        ),
    ]
