# Generated by Django 4.2.30 on 2026-09-16 07:59

from django.db import migrations


def migrate_forward(apps, schema_editor):
    MusicItem = apps.get_model("orman", "MusicItem")
    MusicItemPart = apps.get_model("orman", "MusicItemPart")

    # Copy each part's single `instrument` FK into the new `instruments` M2M.
    for part in MusicItemPart.objects.exclude(instrument__isnull=True):
        part.instruments.add(part.instrument_id)

    # Turn each MusicItem's score_file/external_link into a MusicItemPart
    # flagged is_score=True, so the score becomes "just another part".
    # (Iterate + check in Python rather than filter in the query — FileField
    # can store either '' or NULL for "no file" depending on how it was set.)
    for item in MusicItem.objects.all():
        if item.score_file or item.external_link:
            MusicItemPart.objects.create(
                musicItem=item,
                is_score=True,
                file=item.score_file.name if item.score_file else "",
                external_link=item.external_link or "",
            )


def migrate_backward(apps, schema_editor):
    """Best-effort reversal — the old schema has no room for a part covering
    both the score and an instrument, or several instruments at once, so
    those (only reachable via the new feature) collapse to a single choice."""
    MusicItem = apps.get_model("orman", "MusicItem")
    MusicItemPart = apps.get_model("orman", "MusicItemPart")

    for part in MusicItemPart.objects.all():
        first_instrument = part.instruments.first()
        if first_instrument:
            # Restore `instrument` before 0005's AlterField reversal makes it
            # NOT NULL again — every remaining part needs a value.
            part.instrument = first_instrument
            part.save(update_fields=["instrument"])
        elif part.is_score:
            item = part.musicItem
            if part.file:
                item.score_file = part.file.name
            if part.external_link:
                item.external_link = part.external_link
            item.save(update_fields=["score_file", "external_link"])
            part.delete()
        else:
            # Neither scored nor assigned to any instrument — nothing the
            # old schema can represent.
            part.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("orman", "0005_add_musicitempart_instruments_and_score"),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]
