# Generated by Django 4.2.30 on 2026-09-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orman", "0006_migrate_score_and_instrument_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="musicitempart",
            options={"ordering": ["-is_score", "id"]},
        ),
        migrations.RemoveField(
            model_name="musicitem",
            name="external_link",
        ),
        migrations.RemoveField(
            model_name="musicitem",
            name="parts",
        ),
        migrations.RemoveField(
            model_name="musicitem",
            name="score_file",
        ),
        migrations.RemoveField(
            model_name="musicitempart",
            name="instrument",
        ),
    ]
