# Generated by Django 4.2.30 on 2026-09-16 11:57

from django.db import migrations, models
import uuid


def assign_unique_tokens(apps, schema_editor):
    """AddField's `default=uuid.uuid4` only evaluates the callable ONCE and
    applies that single value to every existing row — so without this step,
    every Person that already existed would share the identical mcp_token
    (which, unlike calendar_token, grants full admin API access)."""
    Person = apps.get_model("orman", "Person")
    for person in Person.objects.all():
        person.mcp_token = uuid.uuid4()
        person.save(update_fields=["mcp_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("orman", "0007_remove_legacy_score_and_instrument_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="mcp_token",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Bearer token for the /mcp/ endpoint. Only grants access while the account is an admin.",
                null=True,
                verbose_name="MCP API token",
            ),
        ),
        migrations.RunPython(assign_unique_tokens, migrations.RunPython.noop),
    ]
